name: semantic-release

on:
    push:
        branches:
            - master

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.10.0
            - name: Install semantic-release
              run: npm install -g semantic-release @semantic-release/changelog conventional-changelog-conventionalcommits @semantic-release/git semantic-release-replace-plugin @codedependant/semantic-release-docker
            - name: Publish
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_USERNAME }}
                  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                  DOCKER_REGISTRY: "docker.io"
              run: npx semantic-release